name: DartAngular
description: A Dart app that uses Angular 2
version: 0.0.1
environment:
  sdk: '>=1.19.0 <2.0.0'
dependencies:
  angular2: 2.0.0-beta.21
  browser: ^0.10.0
  dart_to_js_script_rewriter: ^1.0.1
  http: ^0.11.0
  stream_transformers: ^0.3.0
transformers:
- angular2:
    entry_points: web/main.dart
    resolved_identifiers:
            BrowserClient: 'package:http/browser_client.dart'
- dart_to_js_script_rewriter
